window.CHAT_FAQ = [
  {
    id: "what-excel",
    questions: [
      "what excel do i need to upload",
      "what excel should i upload",
      "which excel file",
      "what file do i upload",
      "what workbook do i need",
      "can you tell me the excel format",
      "what is the excel that i need to upload",
      "which file should i use",
      "do you have a template",
      "sample excel",
      "sample file",
      "sample workbook",
      "what format is needed",
      "csv or excel",
      "can i upload csv",
      "what sheets are required",
      "how should the excel look",
      "what all sheets",
      "i dont have the file",
      "where is the sample file",
      "what excel i upload",
      "which excel to upload",
      "excel kaun sa upload karu",
      "kya file chahiye",
      "what to upload",
      "upload kya karna hai",
    ],
    keywords: ["excel", "upload", "file", "workbook", "template", "sample", "sheet", "format", "csv", "xlsx"],
    answer:
      "<p>You need one Excel file (.xlsx), not CSV or PDF.</p><p>It should have these 4 sheets:</p><p class=\"muted\">Employee_Master — your people and current pay<br>Increment_Grid — grade × rating → increment %<br>Salary_Band — min / median / max by department, grade, years at level<br>Salary_Correction_Rules — compa ratio range → correction %</p><p>A ready sample is <em>data/sample_compensation_input.xlsx</em> in the project folder. Attach it with + or drop it here.</p>",
  },
  {
    id: "employee-master",
    questions: [
      "what is employee master",
      "what columns in employee master",
      "what employee data do you need",
      "which employee fields",
      "what should be in the employee sheet",
    ],
    keywords: ["employee", "master", "columns", "fields", "sheet"],
    answer:
      "<p>Employee_Master is the people sheet. Each row is one employee.</p><p class=\"muted\">Needed in practice: Employee ID, Name, Department, Grade, Current Salary, Performance Rating (1–5), Years At Level.<br>Also useful: Designation, Date of Joining, Current Grade Since, Total Years Experience, Location, Reporting Manager, Reporting Partner, Employment Status.</p><p>Salary can be in LPA, like 10 or 10 LPA. IDs must be unique. Missing ID, salary, or grade is flagged and that row is skipped.</p>",
  },
  {
    id: "increment-grid",
    questions: [
      "what is increment grid",
      "how is increment decided",
      "where does increment percent come from",
      "rating increment table",
    ],
    keywords: ["increment", "grid", "hike", "raise", "rating"],
    answer:
      "<p>Increment % comes from the Increment_Grid sheet, not from a guess.</p><p>It matches <em>Grade + Performance Rating</em>. Example: Grade A1 and rating 4 → 10%.</p><p>Rating 1 can still get a salary correction if they are below the band minimum, but their performance increment can be 0%.</p>",
  },
  {
    id: "salary-band",
    questions: [
      "what is salary band",
      "what is min median max",
      "how do you match the band",
      "same department grade years",
    ],
    keywords: ["band", "minimum", "median", "maximum", "market"],
    answer:
      "<p>Salary_Band is the market range for a role.</p><p>I match an employee using <em>Department + Grade + Years At Level</em>. People with the same three always use the same band.</p><p class=\"muted\">Example: Technology, A1, 2 years → Min 11 LPA, Median 14 LPA, Max 20 LPA.</p>",
  },
  {
    id: "correction-rules",
    questions: [
      "what is salary correction",
      "what are correction rules",
      "why correction percent",
      "compa correction",
    ],
    keywords: ["correction", "compa", "rules"],
    answer:
      "<p>Salary correction is extra % to move someone closer to market, based on compa ratio.</p><p class=\"muted\">Below 0.80 → 8%<br>0.80 to 0.90 → 5%<br>0.90 to 1.00 → 2%<br>1.00 and above → 0%</p><p>If pay is below the band minimum, correction still applies even if the rating is low. If pay is above the band maximum, correction is withheld. Only the performance increment applies then.</p>",
  },
  {
    id: "how-it-works",
    questions: [
      "how does this work",
      "how do you calculate",
      "how is recommended salary calculated",
      "how is recommended salary",
      "how the salary is calculate",
      "how the salary is calculated",
      "how salary is calculate",
      "how salary is calculated",
      "how salary calculated",
      "how u calculate salary",
      "how you calculate salary",
      "how do u calculate the salary",
      "how do i calculate salary",
      "how we calculate salary",
      "how this salary come",
      "how new salary come",
      "how recommended salary come",
      "how hike is calculated",
      "how increment is calculated",
      "salary calculation",
      "salary formula",
      "formula of salary",
      "what is the formula",
      "how is new salary calculated",
      "explain the logic",
      "how do you recommend salary",
      "tell me how salary is calculated",
      "pls tell how salary calculated",
      "kaise salary calculate",
      "salary kaise nikalte",
      "salary kaise calculate hota hai",
      "calc salary",
      "calculate recommended salary",
    ],
    keywords: ["how", "calculate", "formula", "recommend", "logic", "work", "salary", "hike", "basis"],
    answer:
      "<p>1. Find the salary band by department, grade, and years at level<br>2. Compa ratio = current salary ÷ median<br>3. Salary position against min / median / max<br>4. Correction % from compa rules<br>5. Increment % from grade × performance rating<br>6. Total increase = increment + correction<br>7. Recommended salary = current × (1 + total increase)</p><p>Example: 10 LPA, median 14, rating 4 → 10% + 8% = 18% → 11.8 LPA.</p><p class=\"muted\">If Increment_Grid, Salary_Band, or Correction_Rules are in your Excel, those values are used. If they are missing, the built-in formulas below are used.</p>",
  },
  {
    id: "basis-all",
    questions: [
      "on what basis these are calculate",
      "on what basis these are calculated",
      "on what basis this is calculated",
      "on what basis is this calculated",
      "on what basis the salary is calculate",
      "on what basis increment is calculated",
      "on what basis correction is calculated",
      "on what basis recommended salary is calculated",
      "what formula do you use",
      "predefined formula",
      "built in formula",
      "default formula",
      "which formula you applied",
      "basis of calculation",
      "on what basis",
      "how these numbers come",
      "explain all formulas",
    ],
    keywords: ["basis", "formula", "predefined", "default", "increment", "correction", "calculate"],
    answer:
      "<p>Here is the basis, in the same order I calculate.</p><p><em>Salary band</em><br>Match department + grade + years at level.<br>If your Salary_Band sheet is present, I use that. If not, I use the built-in band for that grade. For A1 at 2 years the built-in is Min 11, Median 14, Max 20 LPA.</p><p><em>Compa ratio</em><br>Current salary ÷ median salary.<br>Example: 10 ÷ 14 = 0.71.</p><p><em>Increment %</em><br>From Increment_Grid: Grade × Performance Rating.<br>If that sheet is missing, the built-in grid is: rating 5 = 15%, 4 = 10%, 3 = 7%, 2 = 3%, 1 = 0%.</p><p><em>Salary correction %</em><br>From Salary_Correction_Rules using compa.<br>If that sheet is missing, the built-in rules are:<br>below 0.80 → 8%<br>0.80 to 0.90 → 5%<br>0.90 to 1.00 → 2%<br>1.00 and above → 0%.<br>Below band minimum: correction still applies, even if rating is low.<br>Above band maximum: no correction, only performance increment.</p><p><em>Recommended salary</em><br>Current salary × (1 + increment % + correction %).<br>Example: 10 × 1.18 = 11.8 LPA.</p>",
  },
  {
    id: "compa-ratio",
    questions: [
      "what is compa ratio",
      "what does compa mean",
      "explain compa",
      "how is compa calculated",
      "on what basis the compa is calculate",
      "on what basis the compa is calculated",
      "on what basis compa is calculated",
      "on what basis is compa calculated",
      "how the compa is calculate",
      "how the compa is calculated",
      "how compa is calculate",
      "how compa calculated",
      "how u calculate compa",
      "how do you calculate compa",
      "compa kis basis pe",
      "compa kaise nikalte",
      "compa kaise calculate",
      "what is the basis of compa",
      "basis of compa ratio",
      "tell me about compa",
      "compa ratio meaning",
      "compa formula",
      "formula of compa",
      "why we use compa",
    ],
    keywords: ["compa", "ratio", "basis", "median"],
    answer:
      "<p>Compa is calculated on the matched salary band, not on rating alone.</p><p>First I match the employee using department, grade, and years at level. That gives the median salary for the same kind of role. Then:</p><p class=\"muted\">Compa ratio = current salary ÷ median salary</p><p>Example: current 10 LPA, median 14 LPA → 10 ÷ 14 = 0.71.</p><p class=\"muted\">Below 1.00 — below market<br>Around 1.00 — market aligned<br>Above 1.00 — above market</p><p>That compa is what drives salary correction % from your correction rules sheet.</p>",
  },
  {
    id: "salary-position",
    questions: [
      "what is salary position",
      "what is below minimum",
      "what is above band",
      "what is market aligned",
      "below median meaning",
    ],
    keywords: ["position", "below", "minimum", "aligned", "above", "band"],
    answer:
      "<p>Salary position is where current pay sits in the band:</p><p class=\"muted\">Below Minimum — under the band floor<br>Below Median — between min and median<br>Market Aligned — close to median<br>Above Median — between median and max<br>Above Band — over the band maximum</p>",
  },
  {
    id: "how-to-use",
    questions: [
      "how do i use this",
      "how to start",
      "what should i do first",
      "how to generate report",
      "how to compare",
      "how to see budget",
      "how to download",
      "how do i check one employee",
    ],
    keywords: ["how", "use", "start", "generate", "compare", "download"],
    answer:
      "<p>Typical flow:</p><p class=\"muted\">1. Attach or drop the Excel with +<br>2. Type <em>report</em> for everyone<br>3. Type an ID like <em>1001</em> for one person<br>4. Type <em>1001, 1002</em> to compare<br>5. Type <em>budget</em> for cost impact<br>6. Type <em>download report</em> for Excel</p>",
  },
  {
    id: "what-is-this",
    questions: [
      "what is this",
      "what can you do",
      "what is this tool",
      "who is this for",
      "what does this app do",
    ],
    keywords: ["what", "tool", "app", "this", "do"],
    answer:
      "<p>This is a compensation planning chat for HR and reward teams.</p><p>You upload employee pay, increment policy, and salary bands. I apply the rules and give increment %, correction %, compa ratio, recommended salary, comparison, and budget impact.</p>",
  },
  {
    id: "lpa",
    questions: [
      "what is lpa",
      "is salary in lakhs",
      "rupees or lpa",
      "what currency",
    ],
    keywords: ["lpa", "lakh", "salary", "currency", "ctc"],
    answer:
      "<p>Figures are in LPA — lakhs per annum. 10 LPA means 10,00,000 a year.</p><p>You can type 10, 10 LPA, or 1000000. Values of 1000 or more are treated as rupees and converted to LPA.</p>",
  },
  {
    id: "ratings",
    questions: [
      "what ratings are allowed",
      "performance rating scale",
      "invalid rating",
      "rating 1 to 5",
    ],
    keywords: ["rating", "performance", "1", "5", "invalid"],
    answer:
      "<p>Performance rating must be 1 to 5. Anything else is flagged as invalid.</p><p>The increment still comes from Grade + Rating on the Increment_Grid. A low rating does not block salary correction if the person is below the band minimum.</p>",
  },
  {
    id: "errors-validation",
    questions: [
      "why was my file rejected",
      "what errors do you check",
      "duplicate employee",
      "missing salary",
      "validation report",
      "my upload failed",
    ],
    keywords: ["error", "validation", "missing", "duplicate", "failed", "rejected"],
    answer:
      "<p>On upload I check for missing Employee ID, missing salary, missing grade, ratings outside 1–5, and duplicate IDs.</p><p>Bad rows are listed in a validation report. Valid rows are still calculated. You can type <em>download validation</em> after upload.</p>",
  },
  {
    id: "ai-or-not",
    questions: [
      "are you ai",
      "is this machine learning",
      "do you predict attrition",
      "can you recommend retention",
      "is this chatgpt",
    ],
    keywords: ["ai", "ml", "machine", "attrition", "predict", "llm", "gpt"],
    answer:
      "<p>This phase is only rule-based. I do not predict attrition, and I do not use machine learning or a language model to set pay.</p><p>Recommendations come from your increment grid, salary bands, and correction rules.</p>",
  },
  {
    id: "privacy",
    questions: [
      "is my data saved",
      "where is the data stored",
      "do you send data outside",
      "is this confidential",
    ],
    keywords: ["data", "saved", "store", "privacy", "confidential"],
    answer:
      "<p>The workbook stays in this session on the local app. Refresh or restart and you upload again. I do not send the file to an outside AI service.</p>",
  },
  {
    id: "budget-q",
    questions: [
      "what is budget impact",
      "what does increment cost mean",
      "what is correction cost",
      "how is payroll calculated",
    ],
    keywords: ["budget", "payroll", "cost", "increment cost"],
    answer:
      "<p>Budget impact is the money side of the cycle.</p><p class=\"muted\">Current payroll — what you pay today<br>Proposed payroll — after recommended salaries<br>Increment cost — cost from performance hikes<br>Correction cost — cost from market corrections<br>Total compensation cost — increment + correction</p><p>Type <em>budget</em> after you upload.</p>",
  },
  {
    id: "compare-q",
    questions: [
      "how do i compare two people",
      "how to compare employees",
      "can i compare more than two",
    ],
    keywords: ["compare", "comparison", "two", "employees"],
    answer:
      "<p>Type two or more IDs, like <em>1001, 1002</em>.</p><p>I put them side by side: current salary, grade, rating, years at level, band, compa, increment, correction, and recommended salary.</p>",
  },
  {
    id: "one-employee",
    questions: [
      "how do i see one employee",
      "can i search by employee id",
      "lookup employee",
    ],
    keywords: ["employee", "id", "search", "one", "lookup"],
    answer:
      "<p>After upload, type the ID, like <em>1001</em>.</p><p>I will show that person’s current pay, band, compa, increment, correction, and recommended salary.</p>",
  },
  {
    id: "below-min-rule",
    questions: [
      "why did a low rating still get correction",
      "below minimum correction",
      "poor performer below band",
    ],
    keywords: ["below", "minimum", "low", "rating", "correction"],
    answer:
      "<p>If current salary is below the band minimum, salary correction still applies even if the rating is low. That is to bring pay toward the floor of the band.</p><p>The performance increment can still be 0% for rating 1.</p>",
  },
  {
    id: "above-max-rule",
    questions: [
      "why no correction above max",
      "employee above band",
      "overpaid increment only",
    ],
    keywords: ["above", "maximum", "max", "band", "over"],
    answer:
      "<p>If current salary is above the band maximum, there is no salary correction. Only the performance increment from the grid may apply.</p>",
  },
];
