window.CHAT_PHRASES = {
  fillers: [
    "ok", "okay", "k", "kk", "oh", "ah", "uh", "um", "hmm", "well", "please",
    "just", "really", "so", "very", "much", "a", "an", "the", "lot", "ton", "bunch",
    "mate", "buddy", "bro", "bruh", "man", "dude", "pal", "sir", "mam", "maam", "madam",
    "there", "again", "yeah", "yes", "yep", "yup", "ya", "yea", "also", "too",
    "for", "this", "that", "see", "now", "then", "dear", "friend", "team", "all",
    "and", "to", "you", "u", "ur", "your", "me", "my", "i", "im", "i'm", "am",
    "here", "once", "more", "again", "kindly", "pls", "plz", "pleasee",
  ],
  greetings: [
    "hi", "hii", "hiii", "hiiii", "hello", "helloo", "hellooo", "hellow", "helo",
    "hey", "heyy", "heyyy", "heya", "heyya", "hiya", "howdy", "yo", "yoo", "yooo",
    "hi there", "hey there", "hello there", "hey hi", "hi hi", "hello hi",
    "good morning", "good afternoon", "good evening", "good night", "good day",
    "morning", "afternoon", "evening", "gm", "ga", "ge", "gn", "gud morning",
    "gud afternoon", "gud evening", "gud nyt", "gud night",
    "how are you", "how r you", "how r u", "how ru", "how are u", "hows you",
    "how's it going", "how is it going", "how you doing", "how u doing",
    "how do you do", "whats up", "what's up", "whatsup", "wassup", "wazzup",
    "sup", "wyd", "greetings", "namaste", "namaskar", "vanakkam", "salaam",
    "salam", "assalamualaikum", "as salamu alaykum", "welcome", "hey mate",
    "hi mate", "hello mate", "hey buddy", "hi buddy", "hello buddy",
    "hey bro", "hi bro", "hey man", "hi man", "hey dude", "gday", "g'day",
    "good to see you", "nice to meet you", "pleased to meet you",
  ],
  thanks: [
    "thanks", "thank", "thankyou", "thank you", "thank u", "thanks you",
    "thx", "thnx", "thanx", "thnks", "tks", "ty", "tysm", "tyvm", "tq", "tqs",
    "cheers", "ta", "merci", "dhanyavad", "dhanyavaad", "shukriya", "sukria",
    "thanks a lot", "thanks a ton", "thanks a bunch", "thanks so much",
    "thank you so much", "thank you very much", "thanks very much",
    "many thanks", "much thanks", "much appreciated", "greatly appreciated",
    "appreciate", "appreciated", "appreciate it", "appreciate this",
    "appreciate your help", "thanks for this", "thank you for this",
    "thanks for the help", "thank you for the help", "thanks mate",
    "thank you mate", "thanks buddy", "ok thanks", "okay thanks",
    "ok thank you", "okay thank you", "thanks ok", "thank you so very much",
    "grateful", "i appreciate it", "i appreciate this", "thanks again",
    "thank you again", "thanks a million",
  ],
};
